apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-exporter
  template:
    metadata:
      labels:
        app: prometheus-exporter
    spec:
      containers:
        - name: prometheus-exporter
          image: skaliarman/prometheus:latest1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-exporter
  labels:
    app: prometheus-exporter
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: prometheus-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-exporter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
